spring.application.name=StudentSpringBootUsingDatabase


server.port = 8080

spring.datasource.url = jdbc:mysql://localhost:3306/studentspringbootdb

spring.datasource.username=root
spring.datasource.password=Ashan05@


spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialact = org.hibernate.dialect.MySqlDialect